server:
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/cattinder}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:{cipher}049cfafa52aefcc777d3351dfbaefb574f98302e647ef4a07cd3d1f5c2fd49bc}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    use-root-path: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    com.example: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

catinder:
  banner: "Configuracion centralizada activa"

