spring:
application:
name: intereses-service

datasource:
url: jdbc:postgresql://localhost:5433/intereses-db
username: admin
password: "{cipher}[TU_PASSWORD_ENCRIPTADO]"

jpa:
hibernate:
ddl-auto: update
show-sql: true
properties:
hibernate.format_sql: true

cloud:
config:
import: "optional:configserver:${CONFIG_SERVER_URI:[http://localhost:8888}](http://localhost:8888})"
username: ${CONFIG_SERVER_USER:configuser}
password: ${CONFIG_SERVER_PASSWORD:configpass}
label: ${CONFIG_SERVER_LABEL:main}
profile: ${CONFIG_SERVER_PROFILE:default}

springdoc:
api-docs:
path: /v3/api-docs
swagger-ui:
path: /swagger-ui/index.html

eureka:
instance:
preferIpAddress: true
hostname: localhost
non-secure-port: ${server.port:8080}
instance-id: ${spring.application.name}:${server.port:8080}
client:
register-with-eureka: true
fetch-registry: true
serviceUrl:
defaultZone: [http://localhost:8762/eureka/](http://localhost:8762/eureka/)
registryFetchIntervalSeconds: 5
initialInstanceInfoReplicationIntervalSeconds: 5

management:
endpoints:
web:
exposure:
include: "*"
endpoint:
health:
show-details: always

server:
port: 8082
forward-headers-strategy: framework
error:
include-message: always
include-binding-errors: always
